swagger: '2.0'
info:
  title: xivo-agentd
  description: Agent service
  version: '1.0'
  license:
    name: GPL v3
    url: http://www.gnu.org/licenses/gpl.txt
  contact:
    name: Dev Team
    url: http://wazo.community
    email: dev.wazo@gmail.com
x-xivo-name: agentd
x-xivo-port: 9493
schemes:
- https
securityDefinitions:
  wazo_auth_token:
    type: apiKey
    name: X-Auth-Token
    in: header
security:
- wazo_auth_token: []
basePath: /1.0
consumes:
- application/json
produces:
- application/json
paths:
  /agents:
    get:
      summary: Get the status of all agents.
      description: '**Required ACL:** `agentd.agents.read`'
      operationId: get_agents
      tags:
      - agents
      responses:
        '200':
          description: A list of agent status
          schema:
            $ref: '#/definitions/AgentStatus'
  /agents/logoff:
    post:
      summary: Logoff all agents.
      description: '**Required ACL:** `agentd.agents.logoff.create`'
      operationId: logoff_agents
      tags:
      - agents
      responses:
        '204':
          description: The operation was performed succesfully
  /agents/relog:
    post:
      summary: Relog all agents.
      description: '**Required ACL:** `agentd.agents.relog.create`


        Relog all agents which are currently logged.'
      operationId: relog_agents
      tags:
      - agents
      responses:
        '204':
          description: The operation was performed succesfully
  /agents/by-id/{agent_id}:
    get:
      summary: Get agent status.
      description: '**Required ACL:** `agentd.agents.by-id.{agent_id}.read`'
      operationId: get_agent_by_id
      tags:
      - agent
      parameters:
      - $ref: '#/parameters/AgentID'
      responses:
        '200':
          description: The agent status
          schema:
            $ref: '#/definitions/AgentStatus'
        '404':
          description: Agent does not exist
          schema:
            $ref: '#/definitions/Error'
  /agents/by-number/{agent_number}:
    get:
      summary: Get agent status.
      description: '**Required ACL:** `agentd.agents.by-number.{agent_number}.read`'
      operationId: get_agent_by_number
      tags:
      - agent
      parameters:
      - name: agent_number
        in: path
        description: Agent's number
        required: true
        type: string
      responses:
        '200':
          description: The agent status
          schema:
            $ref: '#/definitions/AgentStatus'
        '404':
          description: Agent does not exist
          schema:
            $ref: '#/definitions/Error'
  /agents/by-id/{agent_id}/login:
    post:
      summary: Log an agent.
      description: '**Required ACL:** `agentd.agents.by-id.{agent_id}.login.create`'
      operationId: login_agent_by_id
      tags:
      - agent
      parameters:
      - $ref: '#/parameters/AgentID'
      - name: body
        in: body
        description: The extension and context on which to log the agent
        required: true
        schema:
          $ref: '#/definitions/LoginInfo'
      responses:
        '204':
          description: The operation was performed succesfully
        '404':
          description: Agent or extension or context does not exist
          schema:
            $ref: '#/definitions/Error'
        '409':
          description: Agent is already logged or another agent is already logged
            on this extension and context
          schema:
            $ref: '#/definitions/Error'
  /agents/by-number/{agent_number}/login:
    post:
      summary: Log an agent.
      description: '**Required ACL:** `agentd.agents.by-number.{agent_number}.login.create`'
      operationId: login_agent_by_number
      tags:
      - agent
      parameters:
      - name: agent_number
        in: path
        description: Agent's number
        required: true
        type: integer
      - name: body
        in: body
        description: The extension and context on which to log the agent
        required: true
        schema:
          $ref: '#/definitions/LoginInfo'
      responses:
        '204':
          description: The operation was performed succesfully
        '404':
          description: Agent or extension or context does not exist
          schema:
            $ref: '#/definitions/Error'
        '409':
          description: Agent is already logged or another agent is already logged
            on this extension and context
          schema:
            $ref: '#/definitions/Error'
  /agents/by-id/{agent_id}/logoff:
    post:
      summary: Logoff an agent.
      description: '**Required ACL:** `agentd.agents.by-id.{agent_id}.logoff.create`'
      operationId: logoff_agent_by_id
      tags:
      - agent
      parameters:
      - $ref: '#/parameters/AgentID'
      responses:
        '204':
          description: The operation was performed succesfully
        '409':
          description: Agent does not exist or is not logged
          schema:
            $ref: '#/definitions/Error'
  /agents/by-number/{agent_number}/logoff:
    post:
      summary: Logoff an agent.
      description: '**Required ACL:** `agentd.agents.by-number.{agent_number}.logoff.create`'
      operationId: logoff_agent_by_number
      tags:
      - agent
      parameters:
      - name: agent_number
        in: path
        description: Agent's number
        required: true
        type: integer
      responses:
        '204':
          description: The operation was performed succesfully
        '409':
          description: Agent does not exist or is not logged
          schema:
            $ref: '#/definitions/Error'
  /agents/by-number/{agent_number}/pause:
    post:
      summary: Pause an agent.
      description: '**Required ACL:** `agentd.agents.by-number.{agent_number}.pause.create`'
      operationId: pause_agent_by_number
      tags:
      - agent
      parameters:
      - name: agent_number
        in: path
        description: Agent's number
        required: true
        type: integer
      - name: body
        in: body
        description: The reason when pause the agent
        required: false
        schema:
          $ref: '#/definitions/AgentPauseReason'
      responses:
        '204':
          description: The operation was performed succesfully
        '404':
          description: Agent does not exist
          schema:
            $ref: '#/definitions/Error'
        '409':
          description: Agent is not logged
          schema:
            $ref: '#/definitions/Error'
  /agents/by-number/{agent_number}/unpause:
    post:
      summary: Unpause an agent.
      description: '**Required ACL:** `agentd.agents.by-number.{agent_number}.unpause.create`'
      operationId: unpause_agent_by_number
      tags:
      - agent
      parameters:
      - name: agent_number
        in: path
        description: Agent's number
        required: true
        type: integer
      responses:
        '204':
          description: The operation was performed succesfully
        '404':
          description: Agent does not exist
          schema:
            $ref: '#/definitions/Error'
        '409':
          description: Agent is not logged
          schema:
            $ref: '#/definitions/Error'
  /agents/by-id/{agent_id}/add:
    post:
      summary: Add agent to a queue.
      description: '**Required ACL:** `agentd.agents.by-id.{agent_id}.add.create`'
      operationId: add_agent_by_id
      tags:
      - agent
      parameters:
      - $ref: '#/parameters/AgentID'
      - name: body
        in: body
        description: The queue to add the agent to
        required: true
        schema:
          $ref: '#/definitions/Queue'
      responses:
        '204':
          description: The operation was performed succesfully
        '404':
          description: Agent or queue does not exist
          schema:
            $ref: '#/definitions/Error'
        '409':
          description: Agent is already a member of the queue
          schema:
            $ref: '#/definitions/Error'
  /agents/by-id/{agent_id}/remove:
    post:
      summary: Remove agent from a queue.
      description: '**Required ACL:** `agentd.agents.by-id.{agent_id}.remove.create`'
      operationId: remove_agent_by_id
      tags:
      - agent
      parameters:
      - $ref: '#/parameters/AgentID'
      - name: body
        in: body
        description: The queue to remove the agent from
        required: true
        schema:
          $ref: '#/definitions/Queue'
      responses:
        '204':
          description: The operation was performed succesfully
        '404':
          description: Agent or queue does not exist
          schema:
            $ref: '#/definitions/Error'
        '409':
          description: Agent is not a member of the queue
          schema:
            $ref: '#/definitions/Error'
parameters:
  AgentID:
    name: agent_id
    in: path
    type: integer
    required: true
    description: Agent's ID
  recurse:
    name: recurse
    in: query
    type: boolean
    description: Should the query include sub-tenants
    default: false
    required: false
  tenantuuid:
    name: Wazo-Tenant
    type: string
    in: header
    description: "The tenant's UUID, defining the ownership of a given resource."
    required: false
definitions:
  AgentStatus:
    title: Agent status
    properties:
      id:
        type: integer
        format: int32
        description: Agent's ID
      tenant_uuid:
        type: string
        format: uuid
        description: Tenant's UUID
      origin_uuid:
        type: string
        format: uuid
        description: Wazo's UUID
      number:
        type: string
        description: Agent's number
      logged:
        type: boolean
        description: True if the agent is logged, else false
      paused:
        type: boolean
        description: True if the agent is paused, else false
      paused_reason:
        type: string
        description: The reason of the agent pause
      extension:
        type: string
        description: The extension on which the agent is logged, or null if the agent
          is not logged
      context:
        type: string
        description: The context on which the agent is logged, or null if the agent
          is not logged
      state_interface:
        type: string
        description: The interface (e.g. SIP/alice) to determine if the agent is in
          use or not
  LoginInfo:
    title: Login information
    properties:
      extension:
        type: string
        description: Extension
      context:
        type: string
        description: Context
  Queue:
    title: Queue
    properties:
      queue_id:
        type: integer
        description: Queue's ID
  AgentPauseReason:
    title: Pause reason information
    properties:
      reason:
        type: string
        description: Pause Reason
  Error:
    title: Error
    properties:
      error:
        type: string
        description: Error identifier
